Repository Side-Project-Planting/Frontend, pull requests merged in 2023-11, with the labels that each got.

#71 [#33] 플랜 설정, 생성 페이지 공통 컴포넌트 분리
  src/components/InputField.tsx
  src/components/ManageTeam.tsx
  src/pages/CreatePlan.tsx
  src/pages/Setting.tsx
  src/types/index.ts
Labels: Refactor

#72 [#70] 할 일 삭제 및 플랜, 설정 페이지 모달 연결
  src/components/Modal/AddTask.tsx
  src/components/Modal/ExitPlan.tsx
  src/components/Modal/Normal.tsx
  src/components/Modal/index.tsx
  src/components/Tab.tsx
  src/components/TaskItem.tsx
  src/hooks/useModal.tsx
  src/pages/Plan.tsx
  src/pages/Setting.tsx
  src/recoil/atoms.ts
  src/types/index.ts
Labels: feature, Refactor

#74 [#73] 할 일 수정 모달 구현
  public/dummy/planInfo-1.json
  src/components/DateRange.tsx
  src/components/Modal/AddTask.tsx
  src/components/Modal/CommonModalStyles.ts
  src/components/Modal/EditTask.tsx
  src/components/Modal/ExitPlan.tsx
  src/components/Modal/Normal.tsx
  src/components/Modal/index.tsx
  src/components/Tab.tsx
  src/components/TaskItem.tsx
  src/pages/Plan.tsx
  src/pages/Setting.tsx
  src/styles/GlobalStyle.ts
  src/types/index.ts
Labels: feature, Refactor

#76 [#75]팀원 초대시 이메일 유효성 검사 추가
  src/pages/CreatePlan.tsx
  src/pages/Setting.tsx
Labels: feature

#78 [#77] 탭 추가, 이름 변경시 input에 바로 focus되지 않던 버그 해결
  public/dummy/planInfo-1.json
  src/components/Tab.tsx
  src/pages/CreatePlan.tsx
  src/pages/Plan.tsx
Labels: bugfix

#80 [#79] 구글 OAuth 로직 리팩토링
  src/pages/GoogleOauthCallback.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: Refactor

#81 [#64] 1차 배포 테스트 수정 사항 반영
  src/pages/GoogleOauthCallback.tsx
  src/pages/SignIn.tsx
  src/setupProxy.js
Labels: deploy

#84 [#82] 플랜 생성 페이지 연결
  src/components/Header.tsx
Labels: feature

#85 [#83] 탭 삭제시 모달 추가
  src/components/Tab.tsx
  src/pages/Main.tsx
  src/pages/Plan.tsx
Labels: feature

#87 [#86] 라우터 수정 및 auth-service api 연결
  src/App.tsx
  src/components/BriefPlan.tsx
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/components/Logo.tsx
  src/components/Tab.tsx
  src/pages/CreatePlan.tsx
  src/pages/GoogleOauthCallback.tsx
  src/pages/SignUp.tsx
Labels: deploy, Refactor

#89 [#88] 팀원 추가 시 폼이 제출되는 버그 수정
  src/pages/CreatePlan.tsx
Labels: bugfix

#91 [#90] API를 연결하면서 발생한 변경사항 반영
  src/App.tsx
  src/components/Header.tsx
  src/components/Modal/AddTask.tsx
  src/components/Tab.tsx
  src/pages/CreatePlan.tsx
  src/pages/Plan.tsx
  src/recoil/atoms.ts
  src/types/index.ts
Labels: feature

#95 [#94] 메인 페이지 개인 플랜 삭제 및 비어있을때 디자인 변경
  src/assets/images/noPlan.svg
  src/components/BriefPlan/index.tsx
  src/pages/Main/index.tsx
  src/pages/Main/styles.ts
Labels: feature

#97 [#96] 뒤로 가기시 헤더 아이콘 선택이 제대로 안되는 버그 수정
  src/components/Header/index.tsx
Labels: bugfix

#99 [#98] 일부 API 연결 작업 (플랜, 태스크)
  src/apis/index.ts
  src/components/LabelInput/index.tsx
  src/components/Modal/AddTask.tsx
  src/components/Modal/EditTask.tsx
  src/components/Tab/index.tsx
  src/components/TaskItem/index.tsx
  src/pages/Plan/index.tsx
Labels: feature, deploy

#101 [#100] 플랜 설정 api 연동 및 플랜 삭제, 생성 시 currentPageId 버그 수정
  src/components/ManageTeam/index.tsx
  src/components/MemberFilter/index.tsx
  src/pages/CreatePlan/index.tsx
  src/pages/Plan/index.tsx
  src/pages/Setting/index.tsx
  src/types/index.ts
Labels: bugfix, deploy

#104 [#102] 탭 api 연동(보류)
  src/components/Tab/index.tsx
  src/pages/Plan/index.tsx
Labels: deploy

#106 [#105] 플랜 수정 api 명세 변경에 따른 수정
  src/components/Tab/index.tsx
  src/pages/Setting/index.tsx
Labels: deploy

#107 [#103] Task Interface를 API 명세를 반영하여 통일
  src/apis/index.ts
  src/components/Modal/AddTask.tsx
  src/components/Modal/EditTask.tsx
  src/components/TaskItem/index.tsx
  src/pages/CreatePlan/index.tsx
  src/pages/Plan/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/types/index.ts
Labels: Refactor

#109 [#108] 로그인 시 토큰 저장 방식 변경 및 refresh 토큰으로 access 토큰 발급
  package.json
  src/pages/CreatePlan/index.tsx
  src/pages/GoogleOauthCallback/index.tsx
  src/pages/Plan/index.tsx
  src/pages/Setting/index.tsx
  src/setupProxy.js
  src/utils/auth.ts
  yarn.lock
Labels: bugfix, Refactor

#113 [#111, #112] 생성된 플랜이 없을때 플랜페이지 화면, React-Query 설정
  package.json
  src/App.tsx
  src/assets/images/emptyPlan.svg
  src/pages/Plan/index.tsx
  src/pages/Plan/styles.ts
  yarn.lock
Labels: feature

#114 [Deploy test] netlify 배포를 위한 toml 파일 정의
  netlify.toml
  public/index.html
Labels: docs

#115 chore: 배포 관련 설정 추가
  netlify.toml
  package.json
Labels: deploy

#116 [Deploy test] Netlify Proxy 설정 추가
  netlify.toml
  package.json
  src/apis/index.ts
  src/components/Tab/index.tsx
  src/pages/GoogleOauthCallback/index.tsx
  src/pages/Plan/index.tsx
  src/pages/Setting/index.tsx
  src/utils/auth.ts
Labels: deploy

#117 [Deploy test] toml 파일 변경
  netlify.toml
  src/apis/index.ts
  src/components/Tab/index.tsx
  src/pages/GoogleOauthCallback/index.tsx
  src/pages/Plan/index.tsx
  src/pages/Setting/index.tsx
  src/utils/auth.ts
Labels: deploy

#118 [Deploy test] http -> https 및 프록시 삭제, axios 객체를 이용하여 요청하도록 수정
  netlify.toml
  src/apis/index.ts
  src/components/Tab/index.tsx
  src/pages/GoogleOauthCallback/index.tsx
  src/pages/Plan/index.tsx
  src/pages/Setting/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/setupProxy.js
  src/utils/auth.ts
Labels: feature, bugfix, Refactor

#120 [#110] profileUrl 못 받아오는 문제 해결 및 회원가입시 헤더에 accessToken들어가도록 수정
  src/pages/GoogleOauthCallback/index.tsx
  src/pages/SignUp/index.tsx
  src/utils/auth.ts
Labels: bugfix
