Repository Side-Project-Planting/Frontend, pull requests merged in 2023-10, with the labels that each got.

#17 [#12] 공통 헤더, 드롭다운 컴포넌트 구현
  package.json
  src/App.tsx
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/pages/CreatePlan.tsx
  src/pages/Main.tsx
  src/pages/SignIn.tsx
  tsconfig.json
  yarn.lock
Labels: feature

#20 [#14] 공통 셀렉트박스, 모달 컴포넌트 구현
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yml
  src/components/Modal.tsx
  src/components/SelectBox.tsx
  src/hooks/useModal.tsx
Labels: feature, docs

#21 [#15] 플랜 생성 페이지 구현
  src/assets/images/boardIllust.svg
  src/components/Header.tsx
  src/components/ToggleSwitch.tsx
  src/pages/CreatePlan.tsx
  src/styles/GlobalStyle.ts
Labels: feature

#34 [#13] 메인 페이지 UI 구현
  src/assets/images/noData.svg
  src/assets/images/noTeamPlan.svg
  src/components/BriefPlan.tsx
  src/pages/Main.tsx
Labels: feature

#36 [#11] Google OAuth 연동
  package.json
  src/App.tsx
  src/pages/GoogleOauthCallback.tsx
  src/pages/SignIn.tsx
  src/setupProxy.js
  yarn.lock
Labels: feature, bugfix

#37 [#23] 플랜 페이지 UI 구현
  src/App.tsx
  src/components/Header.tsx
  src/components/LabelFilter.tsx
  src/components/MemberFilter.tsx
  src/components/Tab.tsx
  src/pages/Plan.tsx
  src/styles/GlobalStyle.ts
Labels: feature

#38 [#26] 할 일 생성 모달 구현
  public/index.html
  src/assets/images/deadlineCheck.svg
  src/components/BriefPlan.tsx
  src/components/Modal.tsx
  src/components/Modal/AddTask.tsx
  src/components/Modal/CommonModalStyles.ts
  src/components/Modal/ExitPlan.tsx
  src/components/Modal/Normal.tsx
  src/components/Modal/Portal.tsx
  src/components/Modal/index.tsx
  src/components/SelectBox.tsx
  src/types/Plan.ts
  src/utils/index.ts
Labels: feature, bugfix, Refactor

#39 [#22] 탭 추가 구현
  public/dummy/planInfo.json
  src/api/index.ts
  src/components/Tab.tsx
  src/pages/Plan.tsx
  src/styles/GlobalStyle.ts
Labels: feature

#41 [#40] 할 일 추가 모달 레이블 검색 기능 추가
  src/assets/images/startDate.svg
  src/components/Modal/AddTask.tsx
  src/components/Modal/index.tsx
Labels: feature

#43 [#42] Path Alias, Import order 적용
  .eslintrc.json
  .vscode/settings.json
  craco.config.js
  package.json
  src/@types/index.d.ts
  src/App.tsx
  src/apis/index.ts
  src/components/BriefPlan.tsx
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/components/LabelFilter.tsx
  src/components/Logo.tsx
  src/components/MemberFilter.tsx
  src/components/Modal/AddTask.tsx
  src/components/Modal/ExitPlan.tsx
  src/components/Modal/Normal.tsx
  src/components/Modal/Portal.tsx
  src/components/Modal/index.tsx
  src/components/SelectBox.tsx
  src/components/Tab.tsx
  src/components/ToggleSwitch.tsx
  src/hooks/useModal.tsx
  src/index.tsx
  src/pages/CreatePlan.tsx
  src/pages/GoogleOauthCallback.tsx
  src/pages/Main.tsx
  src/pages/Plan.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/styles/GlobalFont.ts
  src/types/index.ts
  src/utils/index.ts
  tsconfig.json
  tsconfig.paths.json
  yarn.lock
Labels: docs

#45 [#44] 플랜페이지에 할 일 추가 모달 연동
  public/dummy/planInfo.json
  src/components/Dropdown.tsx
  src/components/Modal/AddTask.tsx
  src/components/Modal/ExitPlan.tsx
  src/components/Modal/index.tsx
  src/components/SelectBox.tsx
  src/components/Tab.tsx
  src/pages/Plan.tsx
Labels: feature, bugfix

#46 [#28] 라벨 필터링 구현
  public/dummy/planInfo.json
  src/components/LabelFilter.tsx
  src/components/Tab.tsx
  src/pages/Plan.tsx
Labels: feature

#48 [#29] 플랜 데이터 형태 변경에 따른 수정 및 탭 삭제 기능 구현
  public/dummy/planInfo-1.json
  src/apis/index.ts
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/components/Tab.tsx
  src/pages/Plan.tsx
Labels: feature

#50 [#49] 탭 타이틀 수정 구현
  src/components/Dropdown.tsx
  src/components/Tab.tsx
  src/pages/Plan.tsx
Labels: feature

#51 [#47] 할일 아이템 구현
  public/dummy/planInfo.json
  src/components/LabelInput.tsx
  src/components/LabelItem.tsx
  src/components/Modal/AddTask.tsx
  src/components/Modal/ExitPlan.tsx
  src/components/Modal/index.tsx
  src/components/Tab.tsx
  src/components/TaskItem.tsx
  src/hooks/useModal.tsx
  src/pages/Plan.tsx
  src/types/index.ts
Labels: feature, bugfix

#53 [#52] Recoil을 적용하여 labels, members 데이터 처리
  .gitignore
  .vscode/settings.json
  craco.config.js
  package.json
  public/dummy/planInfo-1.json
  src/App.tsx
  src/components/BriefPlan.tsx
  src/components/LabelFilter.tsx
  src/components/LabelInput.tsx
  src/components/LabelItem.tsx
  src/components/Modal/AddTask.tsx
  src/components/Modal/ExitPlan.tsx
  src/components/Modal/Normal.tsx
  src/components/Modal/index.tsx
  src/components/Tab.tsx
  src/components/TaskItem.tsx
  src/pages/Plan.tsx
  src/recoil/atoms.ts
  src/recoil/selectors.ts
  src/types/index.ts
  src/utils/index.ts
  tsconfig.paths.json
  yarn.lock
Labels: feature, bugfix, Refactor

#54 [#24] 탭 정렬, tasks 분류 리팩토링 및 기본적인 탭 drag&drop구현
  src/components/Tab.tsx
  src/pages/Plan.tsx
Labels: feature, Refactor

#56 [#55] 탭 드래그앤드롭 로직 리팩토링
  src/components/Tab.tsx
  src/pages/Plan.tsx
  src/utils/drag.ts
Labels: bug, feature, Refactor

#59 [#58] 탭 드래그앤드롭 버그 수정
  src/pages/Plan.tsx
Labels: bugfix

#61 [#57] 할 일 추가 기능 구현
  src/apis/index.ts
  src/components/LabelInput.tsx
  src/components/LabelItem.tsx
  src/components/Modal/AddTask.tsx
  src/components/Modal/ExitPlan.tsx
  src/components/Modal/index.tsx
  src/components/SelectBox.tsx
  src/pages/Plan.tsx
  src/recoil/atoms.ts
  src/types/index.ts
Labels: feature

#63 [#62] 필터링 리팩토링 및 탭 overflow시 화면 수정
  src/assets/images/allImg.svg
  src/components/MemberFilter.tsx
  src/components/Tab.tsx
  src/pages/Plan.tsx
  src/styles/GlobalStyle.ts
Labels: Refactor

#66 [#25, #65] 할 일 드래그앤드롭 라이브러리 구현
  package.json
  src/components/Modal/AddTask.tsx
  src/components/Modal/index.tsx
  src/components/Tab.tsx
  src/components/TaskItem.tsx
  src/index.tsx
  src/pages/Plan.tsx
  src/utils/drag.ts
  yarn.lock
Labels: feature

#67 [#30] 플랜 설정 페이지 UI 구현
  src/App.tsx
  src/components/SelectBox.tsx
  src/components/TaskItem.tsx
  src/pages/Plan.tsx
  src/pages/Setting.tsx
  src/types/index.ts
Labels: feature

#69 [#68] 할일 드래그앤드롭으로인해 생긴 버그 수정
  src/components/Tab.tsx
  src/components/TaskItem.tsx
  src/pages/Plan.tsx
Labels: bugfix
